### ISSUE TITLE
Tasks waiting in queue indefinitely

### ISSUE THREAD

**Issue by Laudenslager** [Merck/BioPhi#77]
Humanizations tasks are never processed.

**Comment by pdasdana** [comment]
Tasks in queue indefinitely, requests not being processed

**Comment by Epannec** [comment]
Hi, 
We have deployed this last week. Though some changes were required to get it up and running, the platform is behaving as expected once everything is launched. I would therefore consider the fact that this issue might be related to your setup?

Taking the opportunity for a shout-out to to the colleagues from Merck who do the wonderful effort of publishing this platform in the open-source space: you are setting an example! **Thanks!**

**Comment by Laudenslager** [comment]
Thanks for your feedback.  Still getting same lack of response.  This in the online portal we're talking about, right?  Any suggestions on what sorts of things might be a problem on my end so can investigate?


<img width="918" height="298" alt="Image" src="https://github.com/user-attachments/assets/9d879af3-5a2c-4a2f-a7f9-ce2e995d3a00" />

**Comment by Epannec** [comment]
Hi, 
I would suggest getting into the logfiles of the backend to see where the queue is being stopped.

Kind regards,
Erwin

**Comment by Laudenslager** [comment]
It's back up!  Thanks, David Příhoda
